database: # 只针对 gorm  操作数据库有效
  sqlType: "mysql"
  mysql:
    slowThreshold: 30            # 慢 SQL 阈值(sql执行时间超过此时间单位（秒），就会触发系统日志记录)
    write:
      Host: "127.0.0.1"
      name: "novel_plus"   # 数据库名称
      Port: 3306                       #注意，非3306，请自行调整
      user: "root"
      password: "root"
      charset: "utf8"
      setMaxIdleConns: 10
      setMaxOpenConns: 128
      setConnMaxLifetime: 60    # 连接不活动时的最大生存时间(秒)
      #ReConnectInterval: 1    # 保留项,重连数据库间隔秒数
      #PingFailRetryTimes: 3   # 保留项,最大重连次数
    isOpenReadDb: 0                     # 是否开启读写分离配置（1=开启、0=关闭），IsOpenReadDb=1,Read 部分参数有效，否则Read部分参数直接忽略
    read:
      Host: "127.0.0.1"
      name: "novel_plus"      # 数据库名称
      Port: 3308                        #注意，非3306，请自行调整
#      Prefix: "tb_"
      User: "root"
      Pass: "root"
      Charset: "utf8"
      SetMaxIdleConns: 10
      SetMaxOpenConns: 128
      SetConnMaxLifetime: 60